language: node_js
node_js:
  - '10'
  - '8'
script: npm run test

jobs:
  include:
    - stage: analyze
      sudo: required
      dist: trusty
      node_js: '10'
      addons:
        sonarcloud:
          organization: 'jordansinko-github'
      script:
        - npm run test:jest
        - sonar-scanner
